/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loopa.gui;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author up782716
 */
public class LoopaInterface extends javax.swing.JFrame {

    GridBagLayout grid = new GridBagLayout();

    HomePanel homePanel;
    SearchPanel searchPanel;
    AdvancedSettingsPanel advSettingsPanel;



    public LoopaInterface() {

        //Setting up the "Home" , "Search"  panels 

        initComponents();
        this.setLocationRelativeTo(null);
        homePanel = new HomePanel();
        searchPanel = new SearchPanel();
        advSettingsPanel = new AdvancedSettingsPanel();


        changingPanel.setLayout(grid);
        GridBagConstraints gc = new GridBagConstraints();
        gc.gridy = 0;
        gc.gridx = 0;
        changingPanel.add(homePanel, gc);
        changingPanel.add(searchPanel, gc);
        changingPanel.add(advSettingsPanel, gc);



        homePanel.setVisible(true);
        searchPanel.setVisible(false);
        advSettingsPanel.setVisible(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        navigationPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        advSettingsButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        changingPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loopa");

        navigationPanel.setBackground(new java.awt.Color(255, 255, 255));
        navigationPanel.setPreferredSize(new java.awt.Dimension(1200, 150));

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loopa/graphics/home.PNG"))); // NOI18N
        homeButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                homeButtonActionPerformed(evt);
            }
        });

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loopa/graphics/search.PNG"))); // NOI18N
        searchButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                searchButtonActionPerformed(evt);
            }
        });

        advSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loopa/graphics/advanancedSettingsButton.png"))); // NOI18N
        advSettingsButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                advSettingsButtonActionPerformed(evt);
            }
        });

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loopa/graphics/exit.PNG"))); // NOI18N
        exitButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
                navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(navigationPanelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(advSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(58, Short.MAX_VALUE))
        );
        navigationPanelLayout.setVerticalGroup(
                navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(advSettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23))
        );

        getContentPane().add(navigationPanel, java.awt.BorderLayout.PAGE_END);

        changingPanel.setPreferredSize(new java.awt.Dimension(1200, 650));

        javax.swing.GroupLayout changingPanelLayout = new javax.swing.GroupLayout(changingPanel);
        changingPanel.setLayout(changingPanelLayout);
        changingPanelLayout.setHorizontalGroup(
                changingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1209, Short.MAX_VALUE)
        );
        changingPanelLayout.setVerticalGroup(
                changingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 650, Short.MAX_VALUE)
        );

        getContentPane().add(changingPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        homePanel.setVisible(true);
        searchPanel.setVisible(false);
        advSettingsPanel.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_homeButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        homePanel.setVisible(false);
        searchPanel.setVisible(true);
        advSettingsPanel.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void advSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_advSettingsButtonActionPerformed
        homePanel.setVisible(false);
        searchPanel.setVisible(false);
        advSettingsPanel.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_advSettingsButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton advSettingsButton;
    private javax.swing.JPanel changingPanel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
