/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loopa.gui;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import loopa.InvertedBuilder;
import loopa.Loopa;
import loopa.Searcher;
import javax.swing.JOptionPane;

/**
 *
 * @author up782716
 */
public class SearchPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchPanel
     */
    public SearchPanel() {
        initComponents();
        resultsPanel.setVisible(false);
        next.setVisible(false);
        prev.setVisible(false);
        noresultsLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jButton3 = new javax.swing.JButton();
        queryBox = new javax.swing.JTextField();
        querySearchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        resultsPanel = new javax.swing.JPanel();
        result2button = new javax.swing.JButton();
        result3button = new javax.swing.JButton();
        result4button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        result5button = new javax.swing.JButton();
        result1button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        prev = new javax.swing.JButton();
        next = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        noresultsLabel = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 650));

        queryBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                queryBoxActionPerformed(evt);
            }
        });

        querySearchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loopa/graphics/search1.png"))); // NOI18N
        querySearchButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                querySearchButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loopa/graphics/tinyLogo.png"))); // NOI18N

        resultsPanel.setBackground(new java.awt.Color(255, 255, 255));

        result2button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        result2button.setText("http://www.port.ac.uk/staffessentials/");
        result2button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                result2buttonActionPerformed(evt);
            }
        });

        result3button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        result3button.setText("http://www.port.ac.uk/why-portsmouth/");
        result3button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                result3buttonActionPerformed(evt);
            }
        });

        result4button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        result4button.setText("http://www.port.ac.uk/application-fees-and-funding/");
        result4button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                result4buttonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("We’re in the world’s top 100 young universitiesWe’re one of the world’s top 100 young universities The University of Portsmouth is the 98th best young university in the world and the...");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("\"Welcome to Staff Essentials, the online pages providing news, events and useful information for University of Portsmouth staff.\" Research and Innovation Services update Posted ...");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("We have an excellent reputation for quality teaching and sustained, high levels of student satisfaction. Our commitment to preparing you for your future career is evident in every course...");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("The University is committed to fair admissions and to recognising cultural and social diversity and the importance of academic  and other achievements in preparing students to study...");

        result5button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        result5button.setText("http://www.port.ac.uk");
        result5button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                result5buttonActionPerformed(evt);
            }
        });

        result1button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        result1button.setText("http://www.port.ac.uk");
        result1button.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                result1buttonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("The University is committed to fair admissions and to recognising cultural and social diversity and the importance of academic  and other achievements in preparing students to study...");

        prev.setBackground(java.awt.Color.white);
        prev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loopa/graphics/left.png"))); // NOI18N
        prev.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                prevActionPerformed(evt);
            }
        });

        next.setBackground(java.awt.Color.white);
        next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loopa/graphics/right.png"))); // NOI18N
        next.setToolTipText("");
        next.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout resultsPanelLayout = new javax.swing.GroupLayout(resultsPanel);
        resultsPanel.setLayout(resultsPanelLayout);
        resultsPanelLayout.setHorizontalGroup(
                resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultsPanelLayout.createSequentialGroup()
                                .addContainerGap(72, Short.MAX_VALUE)
                                .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(result4button, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(result2button, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(result3button, javax.swing.GroupLayout.PREFERRED_SIZE, 1048, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(result1button, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(resultsPanelLayout.createSequentialGroup()
                                                                .addGap(2, 2, 2)
                                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(resultsPanelLayout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(result5button, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultsPanelLayout.createSequentialGroup()
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2)))
                                .addGap(71, 71, 71))
                        .addGroup(resultsPanelLayout.createSequentialGroup()
                                .addGap(520, 520, 520)
                                .addComponent(prev)
                                .addGap(28, 28, 28)
                                .addComponent(next)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        resultsPanelLayout.setVerticalGroup(
                resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(resultsPanelLayout.createSequentialGroup()
                                .addComponent(result1button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(result2button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(result3button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(result4button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(result5button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(next, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(prev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(45, Short.MAX_VALUE))
        );

        clearButton.setBackground(new java.awt.Color(255, 255, 255));
        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loopa/graphics/clearButton.png"))); // NOI18N
        clearButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                clearButtonActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loopa/graphics/queryQuestion1.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loopa/graphics/results.png"))); // NOI18N

        noresultsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loopa/graphics/noresults2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(resultsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 3, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(202, 202, 202)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(queryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(85, 85, 85)
                                                                .addComponent(jLabel2)
                                                                .addGap(119, 119, 119)
                                                                .addComponent(noresultsLabel))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(134, 134, 134)
                                                                .addComponent(querySearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(queryBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(querySearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel2))
                                                        .addComponent(noresultsLabel)))
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(22, 22, 22)
                                .addComponent(resultsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void querySearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_querySearchButtonActionPerformed


        noresultsLabel.setVisible(false);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loopa/graphics/results.png")));

        Searcher searcher = new Searcher(queryBox.getText(), InvertedBuilder.mapIB);

        if(searcher.result1.equals("no results"))
        {
            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loopa/graphics/noresults1.png")));
            noresultsLabel.setVisible(true);


        }
        else{
            result1button.setText(searcher.result1);
            result2button.setText(searcher.result2);
            result3button.setText(searcher.result3);
            result4button.setText(searcher.result4);
            result5button.setText(searcher.result5);
            resultsPanel.setVisible(true);
        }



    }//GEN-LAST:event_querySearchButtonActionPerformed

    private void result5buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result5buttonActionPerformed
        Loopa.openWebpage(result5button.getText());       // TODO add your handling code here:
    }//GEN-LAST:event_result5buttonActionPerformed

    private void queryBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queryBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_queryBoxActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loopa/graphics/results.png")));
        noresultsLabel.setVisible(false);
        queryBox.setText("");
        resultsPanel.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_clearButtonActionPerformed

    private void result2buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result2buttonActionPerformed
        Loopa.openWebpage(result2button.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_result2buttonActionPerformed

    private void result3buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result3buttonActionPerformed
        Loopa.openWebpage(result3button.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_result3buttonActionPerformed

    private void result4buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result4buttonActionPerformed
        Loopa.openWebpage(result4button.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_result4buttonActionPerformed

    private void result1buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_result1buttonActionPerformed
        Loopa.openWebpage(result1button.getText());
    }//GEN-LAST:event_result1buttonActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        prev.setVisible(true);
        changeResults("next");
        // TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    private void prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevActionPerformed
        changeResults("prev");        // TODO add your handling code here:
    }//GEN-LAST:event_prevActionPerformed

    private void changeResults(String condition)
    {

        if("prev".equals(condition))
        {}
        else
        {}

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    private javax.swing.JButton next;
    private javax.swing.JLabel noresultsLabel;
    private javax.swing.JButton prev;
    public javax.swing.JTextField queryBox;
    private javax.swing.JButton querySearchButton;
    public javax.swing.JButton result1button;
    public javax.swing.JButton result2button;
    public javax.swing.JButton result3button;
    public javax.swing.JButton result4button;
    public javax.swing.JButton result5button;
    private javax.swing.JPanel resultsPanel;
    // End of variables declaration//GEN-END:variables
}
