/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication21;

import java.util.ArrayList;
import java.util.Arrays;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;

/**
 *
 * @author up782716
 */
public class SettingsPanel extends javax.swing.JPanel {

    public boolean crawled = false;
    
    /**
     * Creates new form settingsPanel
     */
    public SettingsPanel() {
        initComponents();
    readyLabel.setVisible(false);
    switchCollectionButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoriesButtonGroup = new javax.swing.ButtonGroup();
        worldOrUk = new javax.swing.ButtonGroup();
        checkURLLabel = new javax.swing.JLabel();
        urlTextBox = new javax.swing.JTextField();
        checkURLButton = new javax.swing.JButton();
        orLabel = new javax.swing.JLabel();
        makeCollectionLabel = new javax.swing.JLabel();
        url3 = new javax.swing.JTextField();
        url1 = new javax.swing.JTextField();
        url2 = new javax.swing.JTextField();
        url4 = new javax.swing.JTextField();
        crawlButton = new javax.swing.JButton();
        categoriesLabel = new javax.swing.JLabel();
        categoriesIcon = new javax.swing.JLabel();
        allRbutton = new javax.swing.JRadioButton();
        newsRbutton = new javax.swing.JRadioButton();
        computersRbutton = new javax.swing.JRadioButton();
        shoppingRbutton = new javax.swing.JRadioButton();
        sportsRbutton = new javax.swing.JRadioButton();
        gamesRbutton = new javax.swing.JRadioButton();
        otherSettingsLabel = new javax.swing.JLabel();
        worldWideButton = new javax.swing.JRadioButton();
        ukButton = new javax.swing.JRadioButton();
        worldOrUkLabel = new javax.swing.JLabel();
        numbersLabel = new javax.swing.JLabel();
        excludeNumbersCheckBox = new javax.swing.JCheckBox();
        stopWordsLabel = new javax.swing.JLabel();
        stopWordsCheckBox = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        readyLabel = new javax.swing.JLabel();
        switchCollectionButton = new javax.swing.JButton();

        setBackground(java.awt.Color.white);
        setMaximumSize(new java.awt.Dimension(1200, 500));
        setMinimumSize(new java.awt.Dimension(1200, 500));

        checkURLLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication21/graphics/advSearchCheckLabel.png"))); // NOI18N

        urlTextBox.setBackground(java.awt.Color.white);
        urlTextBox.setFont(new java.awt.Font("Cantarell", 0, 14)); // NOI18N
        urlTextBox.setText("http://www.example.com");

        checkURLButton.setBackground(java.awt.Color.white);
        checkURLButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication21/graphics/checkButton.png"))); // NOI18N
        checkURLButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkURLButtonActionPerformed(evt);
            }
        });

        orLabel.setBackground(java.awt.Color.white);
        orLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication21/graphics/or.png"))); // NOI18N

        makeCollectionLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication21/graphics/makeCollectionLabel.png"))); // NOI18N

        url3.setBackground(java.awt.Color.white);
        url3.setText("http://bbc.co.uk");

        url1.setBackground(java.awt.Color.white);
        url1.setText("http://www.port.ac.uk");

        url2.setBackground(java.awt.Color.white);
        url2.setText("http://www.cnn.com");

        url4.setBackground(java.awt.Color.white);
        url4.setText("http://www.wikipedia.com");

        crawlButton.setBackground(java.awt.Color.white);
        crawlButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication21/graphics/goButton.png"))); // NOI18N
        crawlButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crawlButtonActionPerformed(evt);
            }
        });

        categoriesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication21/graphics/categories.png"))); // NOI18N

        categoriesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication21/graphics/categoriesNew.png"))); // NOI18N
        categoriesIcon.setToolTipText("");

        categoriesButtonGroup.add(allRbutton);
        allRbutton.setSelected(true);

        categoriesButtonGroup.add(newsRbutton);

        categoriesButtonGroup.add(computersRbutton);

        categoriesButtonGroup.add(shoppingRbutton);

        categoriesButtonGroup.add(sportsRbutton);

        categoriesButtonGroup.add(gamesRbutton);

        otherSettingsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication21/graphics/otherSettings.png"))); // NOI18N

        worldOrUk.add(worldWideButton);

        worldOrUk.add(ukButton);

        worldOrUkLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication21/graphics/worldwideUK.png"))); // NOI18N

        numbersLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication21/graphics/numbers.png"))); // NOI18N

        stopWordsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication21/graphics/stopwordsfinal.png"))); // NOI18N

        readyLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication21/graphics/making2.png"))); // NOI18N

        switchCollectionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication21/graphics/switch1.png"))); // NOI18N
        switchCollectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchCollectionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkURLLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(checkURLButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(urlTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(orLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(crawlButton)
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(makeCollectionLabel)
                            .addGap(50, 50, 50))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(url2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(57, 57, 57)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(url4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(url3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addContainerGap()))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(switchCollectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(worldWideButton)
                            .addComponent(excludeNumbersCheckBox)
                            .addComponent(stopWordsCheckBox))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(worldOrUkLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ukButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stopWordsLabel)
                                    .addComponent(numbersLabel)))))
                    .addComponent(otherSettingsLabel))
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(allRbutton)
                                .addComponent(newsRbutton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(computersRbutton)
                                .addGap(1, 1, 1)))
                        .addGap(35, 35, 35)
                        .addComponent(categoriesIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gamesRbutton)
                            .addComponent(sportsRbutton)
                            .addComponent(shoppingRbutton)))
                    .addComponent(categoriesLabel))
                .addGap(77, 77, 77)
                .addComponent(readyLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(730, Short.MAX_VALUE)
                    .addComponent(url1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(270, 270, 270)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(makeCollectionLabel)
                        .addGap(18, 18, 18)
                        .addComponent(url3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(url2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(url4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(crawlButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkURLLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(urlTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkURLButton)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(readyLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(categoriesLabel)
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(shoppingRbutton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(sportsRbutton)
                                                .addGap(31, 31, 31)
                                                .addComponent(gamesRbutton)
                                                .addGap(12, 12, 12))
                                            .addComponent(categoriesIcon)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(allRbutton)
                                                .addGap(37, 37, 37)
                                                .addComponent(newsRbutton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(computersRbutton)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(switchCollectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(otherSettingsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ukButton)
                                    .addComponent(worldWideButton))
                                .addGap(53, 53, 53)
                                .addComponent(excludeNumbersCheckBox)
                                .addGap(31, 31, 31)
                                .addComponent(stopWordsCheckBox))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(worldOrUkLabel)
                                .addGap(18, 18, 18)
                                .addComponent(numbersLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stopWordsLabel)))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(url1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(494, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crawlButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crawlButtonActionPerformed
        
        readyLabel.setVisible(true);
        readyLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication21/graphics/making2.png"))); // NOI18N
        
        if(stopWordsCheckBox.isSelected())
        {TextAnalyser.useStopWords = false;}
        
        if(excludeNumbersCheckBox.isSelected())
        {TextAnalyser.useNumbers = false;}
        
        //display the correct images:

        orLabel.setVisible(false);
        
        
        createNewCollection(url1.getText(), url2.getText(), url3.getText(), url4.getText());
        
        readyLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication21/graphics/ready.png")));
        switchCollectionButton.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_crawlButtonActionPerformed

    private void createNewCollection(String u1, String u2, String u3, String u4)
    {
        WebCrawler.listOfTraversed.clear();
        WebCrawler.listOfPending.clear();
    WebCrawler.listOfPending.add(u1);
    WebCrawler.listOfPending.add(u2);
    WebCrawler.listOfPending.add(u3);
    WebCrawler.listOfPending.add(u4);
    WebCrawler.crawl(WebCrawler.listOfPending.remove(0));
    InvertedBuilder.mapIB.clear();
    InvertedBuilder.createMap(WebCrawler.listOfTraversed);
    
    }
  
    private void switchCollectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchCollectionButtonActionPerformed
        
        Searcher.source = "all";
        
        readyLabel.setVisible(false);
    
        orLabel.setVisible(true);
    
        switchCollectionButton.setVisible(false);

    }//GEN-LAST:event_switchCollectionButtonActionPerformed

    private void checkURLButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkURLButtonActionPerformed

        if(checkRobots(urlTextBox.getText()).equals("allowed"))
        {orLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication21/graphics/allowsCrawlers.png")));}
        else 
        {
        orLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication21/graphics/noCrawlersAllowed.png")));
        }

// TODO add your handling code here:
    }//GEN-LAST:event_checkURLButtonActionPerformed

     public String checkRobots(String url)
             
    {
        String result = "";
        String robotsURL;
        
    if(!url.endsWith("/"))
    {robotsURL = url.concat("/robots.txt");}
    else 
    {
    robotsURL = url.concat("robots.txt");
    }

//connect to robots.txt
try{
     Document doc = Jsoup.connect(robotsURL).get();
     Elements bodyOf = doc.select("body");
     String robot = bodyOf.text();
    StringBuilder txt = new StringBuilder (); 
    for (int i = robot.indexOf("User-agent: *"); i < robot.length(); i++)
    {
    txt.append(robot.charAt(i));
    }
    String text = txt.toString();
    String [] split = text.split("Disallow: "); 
    ArrayList<String> l = new ArrayList<>();
    l.addAll(Arrays.asList(split));
    l.remove(0);
    for (int i = 0; i<l.size(); i++)
    { 
    l.set(i, url.concat(l.get(i)));
    }
    
    
    
    if(l.get(0).equals(robotsURL))
    {
    result = "not allowed";
    }
    else result = "allowed";
    
 }//try
catch (Exception e)
    {
    result = "allowed";
    }
return result;
 }//getRobots

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allRbutton;
    private javax.swing.ButtonGroup categoriesButtonGroup;
    private javax.swing.JLabel categoriesIcon;
    private javax.swing.JLabel categoriesLabel;
    private javax.swing.JButton checkURLButton;
    private javax.swing.JLabel checkURLLabel;
    private javax.swing.JRadioButton computersRbutton;
    private javax.swing.JButton crawlButton;
    private javax.swing.JCheckBox excludeNumbersCheckBox;
    private javax.swing.JRadioButton gamesRbutton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel makeCollectionLabel;
    private javax.swing.JRadioButton newsRbutton;
    private javax.swing.JLabel numbersLabel;
    private javax.swing.JLabel orLabel;
    private javax.swing.JLabel otherSettingsLabel;
    private javax.swing.JLabel readyLabel;
    private javax.swing.JRadioButton shoppingRbutton;
    private javax.swing.JRadioButton sportsRbutton;
    private javax.swing.JCheckBox stopWordsCheckBox;
    private javax.swing.JLabel stopWordsLabel;
    private javax.swing.JButton switchCollectionButton;
    private javax.swing.JRadioButton ukButton;
    private javax.swing.JTextField url1;
    private javax.swing.JTextField url2;
    private javax.swing.JTextField url3;
    private javax.swing.JTextField url4;
    private javax.swing.JTextField urlTextBox;
    private javax.swing.ButtonGroup worldOrUk;
    private javax.swing.JLabel worldOrUkLabel;
    private javax.swing.JRadioButton worldWideButton;
    // End of variables declaration//GEN-END:variables
}
